#!/usr/bin/env node
'use strict';

const exec = require('child_process').exec;
exec('cat **/*.glsl | ./glc', (error, stdout, stderr) => {
  if (error) {
    console.error(`exec error: ${error}`);
    return;
  }
  console.log(`stdout: ${stdout}`);
  console.log(`stderr: ${stderr}`);
});
